# Generated by Django 3.0.7 on 2020-07-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partes',
            old_name='departamento',
            new_name='claveDepartamento',
        ),
    ]
