# Generated by Django 3.0.7 on 2020-08-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0004_auto_20200813_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctos',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cto.Requisitos'),
        ),
    ]
