# Generated by Django 3.0.7 on 2020-08-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0005_auto_20200815_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctos',
            name='vigenciaIniDocto',
        ),
        migrations.AlterField(
            model_name='doctos',
            name='vigenciaFinDocto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vigencia del documento'),
        ),
    ]
