# Generated by Django 3.0.7 on 2020-08-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0006_auto_20200815_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctos',
            name='pdf2',
            field=models.FileField(default='None/no-img.jpg', upload_to='media/', verbose_name='Archivo del Documento'),
        ),
    ]
