# Generated by Django 3.0.7 on 2020-08-31 18:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0008_auto_20200816_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='actividadesContrato',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Actividades'),
        ),
        migrations.AddField(
            model_name='partes',
            name='estadocivilParte',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='partes',
            name='nacionalidadParte',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='puestos',
            name='actividadesPuesto',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Actividades'),
        ),
    ]
