# Generated by Django 3.0.7 on 2020-09-18 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0009_auto_20200831_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='parte2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cto.Partes', verbose_name='Sujeto del Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='tipocontrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cto.Tipocontrato', verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='totalhorasContrato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de horas'),
        ),
    ]
