# Generated by Django 3.0.7 on 2020-11-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0010_auto_20200917_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='testigoUsual1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Testigo 1'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='testigoUsual2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Testigo 2'),
        ),
    ]
