# Generated by Django 3.0.7 on 2020-11-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0011_auto_20201105_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='testigoUsual1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Testigo usual 1'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='testigoUsual2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Testigo usual 2'),
        ),
    ]
