# Generated by Django 3.0.7 on 2020-12-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0012_auto_20201108_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontrato',
            name='enCalidadDe1',
            field=models.CharField(default='', max_length=150, verbose_name='En calidad de 1'),
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='enCalidadDe2',
            field=models.CharField(default='', max_length=150, verbose_name='En calidad de 2'),
        ),
    ]
