# Generated by Django 3.0.7 on 2021-01-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0014_auto_20201214_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclos',
            name='ciclo_actual',
            field=models.BooleanField(default=False, verbose_name='Ciclo escolar vigente'),
        ),
    ]
