# Generated by Django 3.0.7 on 2021-01-07 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0015_ciclos_ciclo_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='partes',
            name='actividadesParte',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Actividades del puesto'),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='actividadesPuesto',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Actividades del puesto'),
        ),
    ]
