# Generated by Django 3.0.7 on 2021-01-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0016_auto_20210107_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='totalhorasContrato',
            field=models.IntegerField(blank=True, default=40, verbose_name='Total de horas'),
        ),
    ]
