# Generated by Django 3.0.7 on 2021-02-03 13:59

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0017_auto_20210126_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='imppContrato',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1'), default_currency='MXN', max_digits=14, verbose_name='Importe de cada pago'),
        ),
    ]
