# Generated by Django 3.0.7 on 2021-02-07 17:56

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0018_auto_20210203_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='imppContrato',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1'), default_currency='MXN', max_digits=14, null=True, verbose_name='Importe de cada pago'),
        ),
    ]
