# Generated by Django 3.0.7 on 2021-02-09 19:14

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0019_auto_20210207_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='imppContrato',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14, null=True, verbose_name='Importe de cada pago'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='npContrato',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Número de pagos'),
        ),
    ]
