# Generated by Django 3.0.7 on 2021-04-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0021_auto_20210426_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puestos',
            old_name='cpnocimientosPuesto',
            new_name='conocimientosPuesto',
        ),
    ]
