# Generated by Django 3.0.7 on 2021-04-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0025_remove_partes_estatusparte'),
    ]

    operations = [
        migrations.AddField(
            model_name='partes',
            name='estatusParte',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PROSPECTO'), (2, 'EN PROCESO DE CONTRATACION'), (3, 'CONTRATADO'), (4, 'EN PROCESO BAJA VOLUNTARIA'), (5, 'EN PROCESO BAJA NECESARIA'), (6, 'DADO DE BAJA')], default=1),
        ),
    ]
