# Generated by Django 3.0.7 on 2021-04-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0026_partes_estatusparte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partes',
            name='estatusParte',
        ),
    ]
