# Generated by Django 3.0.7 on 2021-05-19 03:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0029_auto_20210428_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partes',
            name='actividadesParte',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Actividades'),
        ),
        migrations.AlterField(
            model_name='partes',
            name='clavePuesto',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cto.Puestos', verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='identificador',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificador'),
        ),
    ]
