# Generated by Django 3.0.7 on 2021-05-20 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0031_partes_personaparte'),
    ]

    operations = [
        migrations.AddField(
            model_name='partes',
            name='datos_representacion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Datos representacion legal'),
        ),
    ]
