# Generated by Django 3.0.7 on 2021-06-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0032_partes_datos_representacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partes',
            name='nombresParte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
    ]
